nodejs:
  applicationPort: 8506
  aadIdentityName: dtsse
  ingressHost: dtsse-ardoq-adapter.{{ .Values.global.environment }}.platform.hmcts.net
  image: 'hmctspublic.azurecr.io/dtsse/ardoq-adapter:latest'
  keyVaults:
    dtsse:
      secrets:
        - AppInsightsConnectionString
        - ardoq-api-key
        - ardoq-api-url
        - ardoq-api-workspace
        - vcs-hosting-workspace
        - code-repository-workspace
        - hmcts-applications-workspace
        - software-frameworks-workspace
        - server-api-key-primary
        - server-api-key-secondary
  environment:
