nodejs:
  applicationPort: 8506
  aadIdentityName: dtsse
  ingressHost: dtsse-ardoq-adapter.{{ .Values.global.environment }}.platform.hmcts.net
  image: 'hmctspublic.azurecr.io/dtsse/ardoq-adapter:latest'
  keyVaults:
    dtsse:
      secrets:
        - AppInsightsConnectionString
        - ardoq-api-key
        - ardoq-api-url
        - ardoq-api-workspace
  environment:
