name: Maintain Ardoq Tech Stack
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - master
      - main
      - fix-github-action
jobs:
  Maintain-Ardoq-Tech-Stack:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3

      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: List dependencies
        run: |
          cat yarn.lock | base64 > yarn.lock.b64
        id: deps

      - name: Prepare request payload
        run: |
          echo '{
            "vcsHost": "github.com/hmcts",
            "hmctsApplication": "dtsse",
            "codeRepository": "${{ github.repository }}",
            "encodedDependecyList": "' > payload.json
          cat yarn.lock.b64 >> payload.json
          echo '",
              "parser": "yarn"
            }' >> payload.json

      - name: debug payload.json
        run: |
          cat payload.json

      - name: compress body
        run: |
          gzip payload.json

      - name: debug compression
        run: |
          ls -lah payload.json.gz

      - name: post deps to ardoq app
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.ARDOQ_ADAPTER_KEY }}" \
            -H "Content-Encoding: gzip" \
            -d @payload.json.gz \
            ${{ secrets.ARDOQ_ADAPTER_URL }}

      - run: echo "🍏 This job's status is ${{ job.status }}."
